//--------------------------------------------
// This file was autogenerated from: /home/guoze.lin/Workspace/MacWorkspace/guoze.lin/thirdparty/turf/cmake/turf_config.h.in
// while running: /home/guoze.lin/Workspace/MacWorkspace/guoze.lin/thirdparty/turf/CMakeLists.txt
// Do not edit!
//--------------------------------------------

#define TURF_HAS_STDINT 1
#define TURF_PREFER_CPP11 0
#define TURF_WITH_BOOST 0
#define TURF_PREFER_BOOST 0
#define TURF_WITH_EXCEPTIONS 0
#define TURF_HAS_NOEXCEPT 1
#define TURF_HAS_CONSTEXPR 1
#define TURF_HAS_OVERRIDE 1
#define TURF_HAS_LONG_LONG 1
#define TURF_REPLACE_OPERATOR_NEW 1
#define TURF_USE_DLMALLOC 0
#define TURF_DLMALLOC_DEBUG_CHECKS 0
#define TURF_DLMALLOC_FAST_STATS 0

#include "turf_userconfig.h"
